# Generated by Django 3.1 on 2020-08-18 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bemember', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
