# Generated by Django 3.1 on 2020-08-20 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bemember', '0002_auto_20200819_0043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='myprofile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='myprofile',
            name='username',
        ),
        migrations.AddField(
            model_name='myprofile',
            name='colorofeyes',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myprofile',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
