# Generated by Django 3.1 on 2020-09-16 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bemember', '0008_auto_20200916_1725'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post',
            new_name='titre',
        ),
    ]
