# Generated by Django 3.1 on 2020-10-01 18:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bemember', '0009_auto_20200916_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateField(default=datetime.date(2020, 10, 1)),
        ),
    ]
