# Generated by Django 3.1 on 2020-10-05 10:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bemember', '0010_auto_20201001_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateField(default=datetime.date(2020, 10, 5)),
        ),
    ]
