# Generated by Django 3.1 on 2020-10-13 18:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bemember', '0012_auto_20201011_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateField(default=datetime.date(2020, 10, 13)),
        ),
    ]
