# Generated by Django 3.1 on 2020-10-05 11:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('caland', '0002_auto_20200911_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2020, 10, 5, 11, 37, 45, 68110, tzinfo=utc)),
        ),
    ]
