# Generated by Django 3.1 on 2020-10-11 10:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('caland', '0003_auto_20201005_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2020, 10, 11, 10, 47, 5, 696055, tzinfo=utc)),
        ),
    ]
