# Generated by Django 3.1 on 2020-10-13 18:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('caland', '0004_auto_20201011_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2020, 10, 13, 18, 56, 51, 656972, tzinfo=utc)),
        ),
    ]
