# Generated by Django 3.1 on 2020-08-19 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='cost',
            field=models.IntegerField(default=150),
        ),
    ]
