# Generated by Django 3.1 on 2020-08-30 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routs', '0002_hotels_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='hotel_Main_Img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
