# Generated by Django 3.1 on 2020-08-30 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routs', '0003_hotels_hotel_main_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotels',
            name='hotel_Main_Img',
            field=models.ImageField(blank=True, default='hotelsample.JPG', null=True, upload_to='images/'),
        ),
    ]
