# Generated by Django 3.1 on 2020-09-10 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routs', '0006_appartement'),
    ]

    operations = [
        migrations.AddField(
            model_name='appartement',
            name='pieces',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='appartement',
            name='surface',
            field=models.IntegerField(default=90),
        ),
    ]
