# Generated by Django 3.1 on 2020-09-12 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routs', '0007_auto_20200910_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotels',
            name='hotel_Main_Img',
            field=models.FileField(default='hotelsample.jpg', null=True, upload_to='images/'),
        ),
    ]
