# Generated by Django 3.1 on 2020-09-14 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routs', '0009_appartement_adresse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appartement',
            old_name='adresse',
            new_name='address',
        ),
    ]
