# Generated by Django 3.1 on 2020-09-15 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routs', '0010_auto_20200914_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='town',
            name='image_town',
            field=models.FileField(default='hotelsample.jpg', null=True, upload_to='images/'),
        ),
    ]
