# Generated by Django 3.1 on 2020-09-16 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routs', '0011_town_image_town'),
    ]

    operations = [
        migrations.AlterField(
            model_name='town',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
