# Generated by Django 3.1 on 2020-09-16 19:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('routs', '0012_auto_20200916_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='likes',
            field=models.ManyToManyField(related_name='hotel_as_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
