# Generated by Django 3.1 on 2020-10-05 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routs', '0014_appartement_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appartement',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='hotels',
            name='likes',
        ),
    ]
