# Generated by Django 3.1 on 2020-10-13 18:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('routs', '0015_auto_20201005_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='appartement',
            name='likes',
            field=models.ManyToManyField(related_name='Appart_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
